name-of-profile:
  outputs:
    dev:
      dataset: dataset-name
      job_execution_timeout_seconds: 1200
      job_retries: 1
      keyfile: C:\gcp_conn\enino-sa.json
      location: US
      method: service-account
      priority: interactive
      project: project-id
      threads: 1
      type: bigquery
  target: dev